[tool.bumpversion]
current_version = "1.1.0"
commit = true
tag = true
message = "Use the Force, Luke. Bump version: {current_version} → {new_version}"

[[tool.bumpversion.files]]
filename = "build.gradle"
search = "{current_version}-SNAPSHOT"
replace = "{new_version}-SNAPSHOT"

